export default [
  {
    label: '用户认证中心',
    name: '用户认证中心',//0105 云鹏
    path: '/basedata',
    component: 'Layout2',
    children: [
      {
        children: [],
        selected: false,
        label: '用户账号',
        name: '/basedata/listAaSubject',
        path: '/basedata/listAaSubject',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '登录认证',
        name: '/basedata/listAaSubjectLogin',
        path: '/basedata/listAaSubjectLogin',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '群组信息',
        name: '/basedata/listAaGroup',
        path: '/basedata/listAaGroup',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '用户所在群组',
        name: '/basedata/listAaSubjectGroup',
        path: '/basedata/listAaSubjectGroup',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '资源权限',
        name: '/basedata/listAaResources',
        path: '/basedata/listAaResources',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '资源群',
        name: '/basedata/listAaResRes',
        path: '/basedata/listAaResRes',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '群组资源',
        name: '/basedata/listAaGroupRes',
        path: '/basedata/listAaGroupRes',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '用户可用资源',
        name: '/basedata/listAaSubjectRes',
        path: '/basedata/listAaSubjectRes',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '群组管理',
        name: '/basedata/listAaGroupAdmin',
        path: '/basedata/listAaGroupAdmin',
        redirect: null,
      }, {
        children: [
          {
            children: [],
            selected: false,
            label: '用户设备',
            name: '/safety/listAaSubjectDevice',
            path: '/safety/listAaSubjectDevice',
            redirect: null,
          }, {
            children: [],
            selected: false,
            label: '用户其他认证信息',
            name: '/safety/listAaSubjectOtherLogin',
            path: '/safety/listAaSubjectOtherLogin',
            redirect: null,
          },
          {
            children: [],
            selected: false,
            label: '用户开关信息',
            name: '/safety/listUserSwitchInfo',
            path: '/safety/listUserSwitchInfo',
            redirect: null,
          },

        ],
        component: 'Layout2',
        label: '账户相关信息',
        name: '账户相关信息',
        path: '/basedata',
      }, {
        children: [],
        selected: false,
        label: '密码修改历史',
        name: '/basedata/listAaSubjectPwdHistory',
        path: '/basedata/listAaSubjectPwdHistory',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '操作日志',
        name: '/basedata/listAaAuditLog',
        path: '/basedata/listAaAuditLog',
        redirect: null,
      }
    ],

  },
  {
    label: '开发案例',
    name: '开发案例',
    path: '/safety',
    component: 'Layout',
    children: [
      {
        children: [],
        selected: false,
        label: '会议管理',
        name: '/safety/listMeetinginfo',
        path: '/safety/listMeetinginfo',
        redirect: null,
      },
    ]
  },
  {
    label: '系统管理',
    name: '系统管理',
    path: '/admin',
    component: 'Layout',
    children: [
      {
        children: [
          {
            children: [],
            selected: false,
            label: '系统配置',
            name: '/basedata/listConfigprop',
            path: '/basedata/listConfigprop',
          },
          {
            children: [],
            selected: false,
            label: '开关设置',
            name: '/safety/listUserSwitchTemp',
            path: '/safety/listUserSwitchTemp',
            redirect: null,
          }, {
            children: [],
            selected: false,
            label: '假期管理',
            name: '/basedata/listPublicHoliday',
            path: '/basedata/listPublicHoliday',
          }, {
            children: [],
            selected: false,
            label: '数据字典类型',
            name: '/basedata/listCodeType',
            path: '/basedata/listCodeType',
          }, {
            children: [],
            selected: false,
            label: '敏感词',
            name: '/basedata/listSensitiveWords',
            path: '/basedata/listSensitiveWords',
          },{
            children: [],
            selected: false,
            label: '敏感词历史',
            name: '/basedata/listSensitiveWordsHis',
            path: '/basedata/listSensitiveWordsHis',
          },

        ],
        selected: false,
        label: '配置管理',
        name: '配置管理',
        path: '/safetyEdu/',
      },
      {
        children: [],
        selected: false,
        label: '我的文件夹',
        name: '我的文件夹',
        path: '/basedata/listFilefolder',
      },
      {
        children: [],
        selected: false,
        label: '信息实体类型',
        name: '信息实体类型',
        path: '/safety/listEntitytype',
      },
      {
        children: [],
        selected: false,
        label: '系统错误日志',
        name: '系统错误日志',
        path: '/basedata/listSystemErrorLog',
        redirect: null,
      },
      {
        children: [],
        selected: false,
        label: ' 监听行为',
        name: ' 监听行为',
        path: '/safety/listAccessmetricsUri',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '用户行为日志',
        name: '用户行为日志',
        path: '/safety/listAmAccesslogentry',
        redirect: null,
      },
      {
        children: [],
        selected: false,
        label: '统计分析',
        name: '统计分析',
        path: '/admin/listStatisticsJobs',
        redirect: null,
      },
      {
        children: [],
        selected: false,
        label: '消息头底部',
        name: '消息头底部',
        path: '/safety/messagetptxt',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '消息模板',
        name: '消息模板',
        path: '/safety/messagetp',
        redirect: null,
      }, {
        children: [],
        selected: false,
        label: '系统消息',
        name: '系统消息',
        path: '/safety/systemmessage',
        redirect: null,
      },

    ]
  },
]
